Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Controllers/TangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Areas.Admin.Controllers.Admin
{
    public class TangController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();

        // GET: Tang
        public ActionResult Index()
        {
            return View(db.tblTangs.ToList());
        }

        // GET: Tang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTang tblTang = db.tblTangs.Find(id);
            if (tblTang == null)
            {
                return HttpNotFound();
            }
            return View(tblTang);
        }

        // GET: Tang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tang/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_tang,ten_tang")] tblTang tblTang)
        {
            if (ModelState.IsValid)
            {
                db.tblTangs.Add(tblTang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblTang);
        }

        // GET: Tang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTang tblTang = db.tblTangs.Find(id);
            if (tblTang == null)
            {
                return HttpNotFound();
            }
            return View(tblTang);
        }

        // POST: Tang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_tang,ten_tang")] tblTang tblTang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblTang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblTang);
        }

        // GET: Tang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTang tblTang = db.tblTangs.Find(id);
            if (tblTang == null)
            {
                return HttpNotFound();
            }
            return View(tblTang);
        }

        // POST: Tang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                tblTang tblTang = db.tblTangs.Find(id);
                db.tblTangs.Remove(tblTang);
                db.SaveChanges();
            }
            catch
            {

            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/Tang/Create.cshtml
@model QLKS.Models.tblTang

@{
    ViewBag.Title = "Thêm Tầng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Tang")">Tầng</a>
    </li>
    <li class="breadcrumb-item active">Thêm tầng</li>
</ol>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tầng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten_tang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten_tang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm tầng" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/Tang/Delete.cshtml
@model QLKS.Models.tblTang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Tang")">Tầng</a>
    </li>
    <li class="breadcrumb-item active">Xóa tầng</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Delete
    </div>
    <div class="card-body">
        <div class="table-responsive">

            <h3>Are you sure you want to delete this?</h3>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        Tầng
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ten_tang)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/Tang/Details.cshtml
@model QLKS.Models.tblTang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblTang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ten_tang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ten_tang)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ma_tang }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/Tang/Edit.cshtml
@model QLKS.Models.tblTang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Tang")">Tầng</a>
    </li>
    <li class="breadcrumb-item active">Sửa thông tin tầng</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Edit
    </div>
    <div class="card-body">
        <div class="table-responsive">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ma_tang)

                    <div class="form-group">
                        @Html.Label("Tầng", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ten_tang, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ten_tang, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/Tang/Index.cshtml
@model IEnumerable<QLKS.Models.tblTang>

@{
    ViewBag.Title = "Danh sách tầng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Danh sách tầng</li>
</ol>
<p>
    <!--@Html.ActionLink("Thêm Tầng", "Create")-->
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh sách các tầng
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>
                        Tầng
                    </th>
                    @if (Session["NV"] != null && ((QLKS.Models.tblNhanVien)Session["NV"]).ma_chuc_vu < 2)
                    {
                        <th></th>
                    }
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ten_tang)
                        </td>
                        @if (Session["NV"] != null && ((QLKS.Models.tblNhanVien)Session["NV"]).ma_chuc_vu < 2)
                        {
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ma_tang }) 
                                <!--@Html.ActionLink("Delete", "Delete", new { id = item.ma_tang })-->
                            </td>
                        }
                    </tr>
                }

            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Last updated at @DateTime.Now</div>
</div>