Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using QLKS.Areas.Admin.Models;
using QLKS.Models;

namespace QLKS.Areas.Admin.Controllers.Admin
{
    public class HoaDonController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();

        // GET: HoaDon
        public ActionResult Index() // return index.cshtml
        {
            var tblHoaDons = 
                db.tblHoaDons.Where(t=>t.ma_tinh_trang==2).
                Include(t => t.tblNhanVien).
                Include(t => t.tblPhieuDatPhong).
                Include(t => t.tblTinhTrangHoaDon);
            double tong = 0;
            foreach (var item in tblHoaDons.ToList())
            {
                if (item.ma_tinh_trang == 2)
                {
                    tong += (double)item.tong_tien;
                }
            }
            ViewBag.tong_tien = String.Format("{0:0,0.00}", tong); // {0,0:C2}
            return View(tblHoaDons.ToList());
        }

        [HttpPost]
        public ActionResult Index(String beginDate, String endDate) // enabled when you need search
        {
            System.Diagnostics.Debug.WriteLine("your message here " + beginDate);
            List<tblHoaDon> dshd = new List<tblHoaDon>();
            String query = "select * from tblHoaDon where ma_tinh_trang=2 ";
            if (!beginDate.Equals(""))
                query += " and ngay_tra_phong >= '" + beginDate + "'";
            if (!endDate.Equals(""))
                query += " and ngay_tra_phong <= '" + endDate + "'";
            
            dshd = db.tblHoaDons.SqlQuery(query).ToList();
            double tong = 0;
            foreach (var item in dshd)
            {
                if (item.ma_tinh_trang == 2)
                {
                    tong += (double)item.tong_tien;
                }
            }
            ViewBag.tong_tien = tong.ToString("C");
            return View(dshd);
        }

        // GET: HoaDon/Details/5
        public ActionResult Details(int? id) // already available
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHoaDon tblHoaDon = db.tblHoaDons.Find(id);
            if (tblHoaDon == null)
            {
                return HttpNotFound();
            }
            return View(tblHoaDon);
        }

        // GET: HoaDon/Create
        public ActionResult Create() // already available
        {
            ViewBag.ma_nv = new SelectList(db.tblNhanViens, "ma_nv", "ho_ten");
            ViewBag.ma_pdp = new SelectList(db.tblPhieuDatPhongs, "ma_pdp", "ma_kh");
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangHoaDons, "ma_tinh_trang", "mo_ta");
            return View();
        }

        // POST: HoaDon/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_hd,ma_pdp,ngay_tra_phong,ma_tinh_trang")] tblHoaDon tblHoaDon) // already available
        {
            if (ModelState.IsValid)
            {
                db.tblHoaDons.Add(tblHoaDon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ma_nv = new SelectList(db.tblNhanViens, "ma_nv", "ho_ten", tblHoaDon.ma_nv);
            ViewBag.ma_pdp = new SelectList(db.tblPhieuDatPhongs, "ma_pdp", "ma_kh", tblHoaDon.ma_pdp);
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangHoaDons, "ma_tinh_trang", "mo_ta", tblHoaDon.ma_tinh_trang);
            return View(tblHoaDon);
        }
        public ActionResult Add(int? id) // return Add.cshtml
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhieuDatPhong tblPhieuDatPhong = db.tblPhieuDatPhongs.Find(id);
            if (tblPhieuDatPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblPhieuDatPhong);
        }
        // GET: HoaDon/Edit/5
        public ActionResult Edit(int? id) // already available
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHoaDon tblHoaDon = db.tblHoaDons.Find(id);
            if (tblHoaDon == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_nv = new SelectList(db.tblNhanViens, "ma_nv", "ho_ten", tblHoaDon.ma_nv);
            ViewBag.ma_pdp = new SelectList(db.tblPhieuDatPhongs, "ma_pdp", "ma_kh", tblHoaDon.ma_pdp);
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangHoaDons, "ma_tinh_trang", "mo_ta", tblHoaDon.ma_tinh_trang);
            return View(tblHoaDon);
        }

        // POST: HoaDon/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_hd,ma_nv,ma_pdp,ngay_tra_phong,ma_tinh_trang,tien_phong,tien_dich_vu,phu_thu,tong_tien")] tblHoaDon tblHoaDon) // already available
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblHoaDon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_nv = new SelectList(db.tblNhanViens, "ma_nv", "ho_ten", tblHoaDon.ma_nv);
            ViewBag.ma_pdp = new SelectList(db.tblPhieuDatPhongs, "ma_pdp", "ma_kh", tblHoaDon.ma_pdp);
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangHoaDons, "ma_tinh_trang", "mo_ta", tblHoaDon.ma_tinh_trang);
            return View(tblHoaDon);
        }

        // GET: HoaDon/Delete/5
        public ActionResult Delete(int? id) // already available
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHoaDon tblHoaDon = db.tblHoaDons.Find(id);
            if (tblHoaDon == null)
            {
                return HttpNotFound();
            }
            return View(tblHoaDon);
        }

        // POST: HoaDon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) // already available
        {
            tblHoaDon tblHoaDon = db.tblHoaDons.Find(id);
            db.tblHoaDons.Remove(tblHoaDon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Result(String ma_pdp,String hoten1,String hoten2,String hoten3,String hoten4,String tuoi1,String tuoi2,String tuoi3,String tuoi4) // return Result.cshtml: đặt phòng thành công
        {
            if (ma_pdp == null)
            {
                return RedirectToAction("Index", "Index");
            }
            else
            {
                List<KhachHang> likh;
                tblPhieuDatPhong pt = db.tblPhieuDatPhongs.Find(Int32.Parse(ma_pdp));
                if (pt.thong_tin_khach_thue == null)
                {
                    likh = new List<KhachHang>();
                    likh.Add(new KhachHang("", ""));
                }
                else
                {
                    likh = JsonConvert.DeserializeObject<List<KhachHang>>(pt.thong_tin_khach_thue);
                }
                if (!hoten1.Equals(""))
                    likh.Add(new KhachHang(hoten1, tuoi1));
                if (!hoten2.Equals(""))
                    likh.Add(new KhachHang(hoten2, tuoi2));
                if (!hoten3.Equals(""))
                    likh.Add(new KhachHang(hoten3, tuoi3));
                if (!hoten4.Equals(""))
                    likh.Add(new KhachHang(hoten4, tuoi4));

                pt.thong_tin_khach_thue = JsonConvert.SerializeObject(likh);
                db.Entry(pt).State = EntityState.Modified;
                db.SaveChanges();
                
                tblHoaDon hd = new tblHoaDon();
                hd.ma_pdp = Int32.Parse(ma_pdp);
                hd.ma_tinh_trang = 1;
                try
                {
                    db.tblHoaDons.Add(hd);
                    tblPhieuDatPhong tgd = db.tblPhieuDatPhongs.Find(Int32.Parse(ma_pdp));
                    if (tgd == null)
                    {
                        return HttpNotFound();
                    }
                    tblPhong p = db.tblPhongs.Find(tgd.ma_phong);
                    if (p == null)
                    {
                        return HttpNotFound();
                    }
                    tgd.ma_tinh_trang = 2;
                    db.Entry(tgd).State = EntityState.Modified;
                    p.ma_tinh_trang = 2;
                    db.Entry(p).State = EntityState.Modified;
                    ViewBag.ngay_ra = tgd.ngay_ra;
                    db.SaveChanges();
                    ViewBag.Result = "success";
                }
                catch
                {
                    ViewBag.Result = "error";
                }
            }
            return View();
        }
        public ActionResult ThanhToan(int? id) // return ThanhToan.cshtml
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/HoaDon/Add.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Nhận Phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Thông tin phiếu đặt phòng</li>
</ol>
<div class="container">

    @using (Html.BeginForm("Result", "HoaDon"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ma_pdp)
        @Html.HiddenFor(model => model.ma_kh)
        @Html.HiddenFor(model => model.ma_phong)
        <div class="form-horizontal">
            <h4>Phiếu đặt phòng</h4>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-4" })
                        @if (Model.ma_kh == null)
                        {
                            try
                            {
                                List<QLKS.Areas.Admin.Models.KhachHang> likh = Newtonsoft.Json.JsonConvert.DeserializeObject<List<QLKS.Areas.Admin.Models.KhachHang>>(Model.thong_tin_khach_thue);
                                <div class="col-md-12">
                                    @Html.TextBox("hoten", likh[0].hoten, new { @class = "form-control", @readonly = "readonly" })
                                </div>
                            }
                            catch { }
                        }
                        else
                        {
                            <div class="col-md-12">
                                @Html.TextBoxFor(u => u.tblKhachHang.ho_ten, null, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        }
                    </div>
                    @if (Model.ngay_dat != null)
                    {
                        <div class="form-group">
                            @Html.Label("Ngày đặt", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-12">
                                @Html.TextBoxFor(u => u.ngay_dat, null, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>
}
                        <div class="form-group">
                            @Html.Label("Ngày vào", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-12">
                                @Html.TextBoxFor(u => u.ngay_vao, null, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Ngày ra", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-12">
                                @Html.TextBoxFor(u => u.ngay_ra, null, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-12">
                                @Html.TextBoxFor(u => u.tblPhong.so_phong, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="col-md-12">
                                <h3 style="line-height:70px">Thông tin khách đi cùng</h3>
                            </div>
                        </div>  

                        <div class="row">
                            <div class="col-md-7">
                                <div class="form-group">
                                    @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.TextBox("hoten1", null, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                @Html.Label("Tuổi", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.TextBox("tuoi1", 18, new { @class = "form-control", type = "number" })
                                </div>
                            </div>
                    </div>

                        <div class="row">
                            <div class="col-md-7">
                                <div class="form-group">
                                    @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.TextBox("hoten2", null, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                @Html.Label("Tuổi", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.TextBox("tuoi2", 18, new { @class = "form-control", type = "number" })
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-7">
                                <div class="form-group">
                                    @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.TextBox("hoten3", null, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                @Html.Label("Tuổi", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.TextBox("tuoi3", 12, new { @class = "form-control", type = "number" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7">
                                <div class="form-group">
                                    @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-12">
                                        @Html.TextBox("hoten4", null, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                @Html.Label("Tuổi", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.TextBox("tuoi4", 12, new { @class = "form-control", type = "number" })
                                </div>
                            </div>
                        </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-12">
                        <input type="submit" value="Nhận phòng" class="btn btn-success btn-lg" />
                    </div>
                </div>
            </div>
        </div>
        }

    <div>
        @Html.ActionLink("Trang chủ", "Index")
    </div>
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/HoaDon/ChiTietHoaDon.cshtml
@model QLKS.Models.tblHoaDon

@{
    ViewBag.Title = "Chi tiết hóa đơn";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Hóa đơn</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Hóa đơn
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @using (Html.BeginForm("XacNhanThanhToan", "HoaDon"))
            {
                @Html.AntiForgeryToken()

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ma_hd)

                            <div class="form-group">
                                @Html.Label("Khách hàng", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.tblPhieuDatPhong.tblKhachHang.ho_ten, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Nhân Viên", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.tblNhanVien.ho_ten, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.ma_nv, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.tblPhieuDatPhong.tblPhong.so_phong, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.tblPhieuDatPhong.tblPhong.so_phong, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Ngày vào phòng", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.EditorFor(m => m.tblPhieuDatPhong.ngay_vao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.tblPhieuDatPhong.ngay_vao, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Ngày dự kiến trả phòng", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.EditorFor(m => m.tblPhieuDatPhong.ngay_ra, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.tblPhieuDatPhong.ngay_ra, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Ngày trả phòng", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.TextBox("ngay_tra_phong", (String)ViewBag.time_now, new { @class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessageFor(model => model.ngay_tra_phong, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Tiền Phòng", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.TextBox("tien_phong", (Double)ViewBag.tien_phong, new { @class = "form-control", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Tiền dịch vụ", htmlAttributes: new { @class = "control-label col-md-8" })
                                <div class="col-md-10">
                                    @Html.TextBox("tien_dich_vu", (Double)ViewBag.tien_dich_vu, new { @class = "form-control", @readonly = "readonly" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card mb-3">
                            <div class="card-header">
                                <i class="fa fa-table"></i> Danh sách dịch vụ đã đặt
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover" cellspacing="0">
                                        <tr>
                                            <th>
                                                Tên dịch vụ
                                            </th>
                                            <th>
                                                Giá
                                            </th>
                                            <th>
                                                Đơn vị
                                            </th>
                                            <th>
                                                Số lượng
                                            </th>
                                            <th>
                                                Thành tiền
                                            </th>
                                        </tr>
                                        @{
                                            List<QLKS.Models.tblDichVuDaDat> ds = (List<QLKS.Models.tblDichVuDaDat>)ViewBag.list_dv;
                                            List<double> tt = (List<double>)ViewBag.list_tt;
                                            for (int i = 0; i < ds.Count; i++)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => ds[i].tblDichVu.ten_dv)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => ds[i].tblDichVu.gia)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => ds[i].tblDichVu.don_vi)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => ds[i].so_luong)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => tt[i])
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </table>

                                </div>

                            </div>

                        </div>
                        <h3>Tổng tiền dịch vụ</h3>
                        @Html.TextBox("tong_tien_dv", (Double)ViewBag.tien_dich_vu, new { @class = "form-control", @readonly = "readonly" })
                    </div>

                </div>
                <hr />
                @*<div class="form-group">
                        @Html.Label("Phụ thu", htmlAttributes: new { @class = "control-label col-md-8" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phu_thu, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phu_thu, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    @Html.Label("Tổng tiền", htmlAttributes: new { @class = "control-label col-md-8" })
                    <div class="col-md-10">
                        @Html.TextBox("tong_tien", (Double)ViewBag.tong_tien, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Trạng thái", htmlAttributes: new { @class = "control-label col-md-8" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.tblTinhTrangHoaDon.mo_ta, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div>
    <input type="button" value="In" onClick="window.print()" class="btn-primary">
    @Html.ActionLink("Quay lại", "Index")
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/HoaDon/DoiPhong.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Gia Hạn Phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("ListPhongDangHoatDong","Index")">Phòng đang hoạt động</a>
    </li>
    <li class="breadcrumb-item active">Đổi phòng @Model.tblPhong.so_phong</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Đổi Phòng @Model.tblPhong.so_phong
    </div>
    <div class="card-body">
        @using (Html.BeginForm("ResultDoiPhong", "HoaDon"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.ma_pdp)
            <div class="form-group">
                @Html.Label("Đổi từ phòng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("ma_phong_cu", Model.tblPhong.so_phong, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Chuyển sang phòng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ma_phong_moi", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ma_phong, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-success">Xác nhận</button>
            </div>
        }
        </div>
    </div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/HoaDon/XacNhanThanhToan.cshtml
@{
    ViewBag.Title = "Thanh toán thành công";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Kết quả</li>
</ol>
@{
    if (ViewBag.result == "success")
    {
        <div class="alert alert-success" role="alert">
            <h2 style="color:#3c763d">Đã hoàn tất thanh toán.</h2>
        </div>
        <div class="alert alert-warning" role="alert"> Phòng được chuyển sang trạng thái dọn phòng! Hay thay đổi trạng thái của phòng sau khi dọn phòng xong !</div>
    }
    else
    {
        <div class="alert alert-danger" role="alert">Có lỗi !<br /></div>
    }
    <a href="@Url.Action("ThanhToan","HoaDon",new { id = ViewBag.ma_hd })">
        <i class="fa fa-arrow-left" aria-hidden="true"></i> Quay lại hóa đơn
    </a> <b> | </b>
    <a href='@Url.Action("Index","Index")'><i class="fa fa-list-ul" aria-hidden="true"></i> Trang chủ </a>
}