Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Controllers/PhieuDatPhongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using QLKS.Areas.Admin.Models;
using QLKS.Models;

namespace QLKS.Areas.Admin.Controllers.Admin
{
    public class PhieuDatPhongController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();

        // GET: PhieuDatPhong
        public ActionResult Index()
        {
            AutoHuyPhieuDatPhong();
            var tblPhieuDatPhongs = db.tblPhieuDatPhongs.Include(t => t.tblKhachHang).Include(t => t.tblPhong).Include(t => t.tblTinhTrangPhieuDatPhong);
            return View(tblPhieuDatPhongs.ToList());
        }

        private void AutoHuyPhieuDatPhong()
        {
            var datenow = DateTime.Now;
            var tblPhieuDatPhongs = db.tblPhieuDatPhongs.Where(u=>u.ma_tinh_trang == 1).Include(t => t.tblKhachHang).Include(t => t.tblPhong).Include(t => t.tblTinhTrangPhieuDatPhong).ToList();
            foreach(var item in tblPhieuDatPhongs)
            {
                System.Diagnostics.Debug.WriteLine((item.ngay_vao - datenow).Value.Days);
                if ((item.ngay_vao - datenow).Value.Days < 0)
                {
                    item.ma_tinh_trang = 3;
                    db.Entry(item).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
        }


        public ActionResult List()
        {
            AutoHuyPhieuDatPhong();
            var tblPhieuDatPhongs = 
                db.tblPhieuDatPhongs.Where(t => t.ma_tinh_trang == 1 && 
                t.ngay_vao.Value.Day == DateTime.Now.Day && 
                t.ngay_vao.Value.Month == DateTime.Now.Month && 
                t.ngay_vao.Value.Year == DateTime.Now.Year).Include(t => t.tblKhachHang).Include(t => t.tblPhong).Include(t => t.tblTinhTrangPhieuDatPhong);
            return View(tblPhieuDatPhongs.ToList());
        }

        // GET: PhieuDatPhong/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhieuDatPhong tblPhieuDatPhong = db.tblPhieuDatPhongs.Find(id);
            if (tblPhieuDatPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblPhieuDatPhong);
        }

        // GET: PhieuDatPhong/Create

        public ActionResult Create(int? id)
        {
            if (id != null)
            {
                ViewBag.select_ma_phong = id;
            }
            ViewBag.ma_kh = new SelectList(db.tblKhachHangs, "ma_kh", "ma_kh");
            ViewBag.ma_phong = new SelectList(db.tblPhongs.Where(u => u.ma_tinh_trang == 1), "ma_phong", "so_phong");
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangPhieuDatPhongs, "ma_tinh_trang", "tinh_trang");
            return View();
        }


        public ActionResult SelectRoom(String dateE)
        {
            if (dateE == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ma_kh = new SelectList(db.tblKhachHangs, "ma_kh", "ma_kh");
            DateTime ngay_ra = (DateTime.Parse(dateE)).AddHours(12);
            ViewBag.ngay_ra = ngay_ra;
            var s = db.tblPhongs.Where(t => !(db.tblPhieuDatPhongs.Where(m=>(m.ma_tinh_trang == 1 || m.ma_tinh_trang ==2) && (m.ngay_ra > DateTime.Now && m.ngay_ra < ngay_ra))).Select(m => m.ma_phong).ToList().Contains(t.ma_phong) && t.ma_tinh_trang == 1);
            ViewBag.ma_phong = new SelectList(s, "ma_phong", "so_phong");
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangPhieuDatPhongs, "ma_tinh_trang", "tinh_trang");
            return View();
        }


        // POST: PhieuDatPhong/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(String radSelect, [Bind(Include = "ma_pdp,ma_kh,ngay_dat,ngay_vao,ngay_ra,ma_phong,ma_tinh_trang")] tblPhieuDatPhong tblPhieuDatPhong, [Bind(Include = "hoten,socmt,tuoi,sodt")] KhachHang kh)
        {
            System.Diagnostics.Debug.WriteLine("SS :"+radSelect);
            if (radSelect.Equals("rad2"))
            {
                tblPhieuDatPhong.ma_kh = null;
                List<KhachHang> likh = new List<KhachHang>();
                likh.Add(kh);
                String ttkh = JsonConvert.SerializeObject(likh);
                tblPhieuDatPhong.thong_tin_khach_thue = ttkh;
            }

                tblPhieuDatPhong.ma_tinh_trang = 1;
                tblPhieuDatPhong.ngay_vao = DateTime.Now;
                tblPhieuDatPhong.ngay_dat = DateTime.Now;
                db.tblPhieuDatPhongs.Add(tblPhieuDatPhong);
                db.SaveChanges();
                int ma = tblPhieuDatPhong.ma_pdp;
                return RedirectToAction("Add","HoaDon",new { id = ma });

            ViewBag.ma_kh = new SelectList(db.tblKhachHangs, "ma_kh", "ma_kh", tblPhieuDatPhong.ma_kh);
            ViewBag.ma_phong = new SelectList(db.tblPhongs, "ma_phong", "so_phong", tblPhieuDatPhong.ma_phong);
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangPhieuDatPhongs, "ma_tinh_trang", "tinh_trang", tblPhieuDatPhong.ma_tinh_trang);
            return View(tblPhieuDatPhong);
        }

        // GET: PhieuDatPhong/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhieuDatPhong tblPhieuDatPhong = db.tblPhieuDatPhongs.Find(id);
            if (tblPhieuDatPhong == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_kh = new SelectList(db.tblKhachHangs, "ma_kh", "mat_khau", tblPhieuDatPhong.ma_kh);
            ViewBag.ma_phong = new SelectList(db.tblPhongs, "ma_phong", "so_phong", tblPhieuDatPhong.ma_phong);
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangPhieuDatPhongs, "ma_tinh_trang", "tinh_trang", tblPhieuDatPhong.ma_tinh_trang);
            return View(tblPhieuDatPhong);
        }

        // POST: PhieuDatPhong/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_pdp,ma_kh,ngay_dat,ngay_vao,ngay_ra,ma_phong,ma_tinh_trang")] tblPhieuDatPhong tblPhieuDatPhong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblPhieuDatPhong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_kh = new SelectList(db.tblKhachHangs, "ma_kh", "mat_khau", tblPhieuDatPhong.ma_kh);
            ViewBag.ma_phong = new SelectList(db.tblPhongs, "ma_phong", "so_phong", tblPhieuDatPhong.ma_phong);
            ViewBag.ma_tinh_trang = new SelectList(db.tblTinhTrangPhieuDatPhongs, "ma_tinh_trang", "tinh_trang", tblPhieuDatPhong.ma_tinh_trang);
            return View(tblPhieuDatPhong);
        }

        // GET: PhieuDatPhong/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPhieuDatPhong tblPhieuDatPhong = db.tblPhieuDatPhongs.Find(id);
            if (tblPhieuDatPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblPhieuDatPhong);
        }

        // POST: PhieuDatPhong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                tblPhieuDatPhong tblPhieuDatPhong = db.tblPhieuDatPhongs.Find(id);
                db.tblPhieuDatPhongs.Remove(tblPhieuDatPhong);
                db.SaveChanges();
            }
            catch
            {

            }
            return RedirectToAction("Index");
        }

    
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/PhieuDatPhong/Create.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Tạo phiếu đật phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Thêm Phiếu Đặt Phòng</li>
</ol>
<p>
    <a href="@Url.Action("Add","KhachHang")">Thêm Tài khoản khách hàng</a>
</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Username", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ma_kh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_kh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày ra", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ngay_ra, new { @type = "date", @class = "form-control",@readonly="readonly" })
                @Html.ValidationMessageFor(model => model.ngay_ra, "", new { @class = "text-danger" })
            </div>
        </div>
        @{
            if (ViewBag.select_ma_phong == null)
            {
                <div class="form-group">
                    @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ma_phong", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ma_phong, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("ma_phong", (int)ViewBag.select_ma_phong, htmlAttributes: new { @class = "form-control",@readonly = "readonly" })
                        
                    </div>
                </div>
                }
            }
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Đặt phòng" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/PhieuDatPhong/Delete.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Xóa phiếu đặt phòng</li>
</ol>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Tên khách hàng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblKhachHang.ho_ten)
        </dd>


        <dt>
            @Html.DisplayName("Ngày đặt")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_dat)
        </dd>


        <dt>
            @Html.DisplayName("Ngày vào")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_vao)
        </dd>

        <dt>
            @Html.DisplayName("Ngày ra")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_ra)
        </dd>


        <dt>
            @Html.DisplayName("Số phòng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblPhong.so_phong)
        </dd>

        <dt>
            @Html.DisplayName("Tình trạng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTinhTrangPhieuDatPhong.tinh_trang)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/PhieuDatPhong/Details.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Thông tin phiếu đặt phòng</li>
</ol>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Tên khách hàng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblKhachHang.ho_ten)
        </dd>


        <dt>
            @Html.DisplayName("Ngày đặt")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_dat)
        </dd>


        <dt>
            @Html.DisplayName("Ngày vào")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_vao)
        </dd>

        <dt>
            @Html.DisplayName("Ngày ra")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngay_ra)
        </dd>


        <dt>
            @Html.DisplayName("Số phòng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblPhong.so_phong)
        </dd>

        <dt>
            @Html.DisplayName("Tình trạng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTinhTrangPhieuDatPhong.tinh_trang)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ma_pdp }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/PhieuDatPhong/Edit.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Sửa phiếu đặt phòng</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ma_pdp)
        @Html.HiddenFor(model => model.ma_kh)
        <div class="form-group">
            @Html.Label("Tên khách hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tblKhachHang.ho_ten, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.ngay_dat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày đặt", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngay_dat, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.ngay_dat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày vào", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ngay_vao, new { @type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ngay_vao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày ra", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ngay_ra, new { @type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ngay_ra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ma_phong", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_phong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tình trang", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ma_tinh_trang", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_tinh_trang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Content/Home/js/main.js"></script>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/PhieuDatPhong/List.cshtml
@model IEnumerable<QLKS.Models.tblPhieuDatPhong>

@{
    ViewBag.Title = "Danh sách phiếu đặt phòng ngày hôm nay";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Danh sách phiếu đặt phòng hôm nay</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh sánh Phiếu đặt phòng ngày hôm nay

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="" cellspacing="0">
                <thead>
                    <tr>
                        <!--
                        <th>
                            @Html.DisplayName("Mã KH")
                        </th>-->
                        <th>
                            @Html.DisplayName("Tên KH")
                        </th>
                        <th>
                            @Html.DisplayName("Ngày đặt")
                        </th>
                        <th>
                            @Html.DisplayName("Ngày vào")
                        </th>
                        <th>
                            @Html.DisplayName("Ngày ra")
                        </th>
                        <th>
                            @Html.DisplayName("Số phòng")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                    <tr>
                        <!--<td>
                            @Html.DisplayFor(modelItem => item.ma_kh)
                        </td>-->
                        <td>
                            @Html.DisplayFor(modelItem => item.tblKhachHang.ho_ten)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ngay_dat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ngay_vao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ngay_ra)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.tblPhong.so_phong)
                        </td>
                        <td>
                            @*@Html.ActionLink("Đặt Phòng", "HoaDon", new { id = item.ma_pdp })*@
                            <a class="nav-link" href="@Url.Action("Add", "HoaDon", new { id = item.ma_pdp })">Nhận Phòng</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at @DateTime.Now</div>
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/PhieuDatPhong/SelectRoom.cshtml
@model QLKS.Models.tblPhieuDatPhong

@{
    ViewBag.Title = "Đặt phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item active">Thêm Phiếu Đặt Phòng</li>
</ol>
<p>
    <a href="@Url.Action("Add","KhachHang")">Thêm Tài khoản khách hàng</a>
</p>
@using (Html.BeginForm("Create", "PhieuDatPhong"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="row">
                <div class="col-md-3">
                    <label class="radio-inline" style="margin-left:40px">
                        @*<input type="radio" name="radSelect" id="rad1" value="rad1" checked="checked">*@
                        @Html.RadioButton("radSelect", "rad1",new { @checked="checked" }) Có tài khoản
                    </label>
                </div>
                <div class="col-md-3">
                    <label class="radio-inline">
                        @*<input type="radio" name="radSelect" id="rad2" value="rad2">*@
                        @Html.RadioButton("radSelect", "rad2")Đăng ký nhanh
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group" id="boxUser">
            @Html.Label("Username", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ma_kh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ma_kh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="boxKH" class="hidden">
            <div class="form-group">
                @Html.Label("Họ tên", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("hoten", null, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Số CMT", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("socmt", null, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Tuổi", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("tuoi", null, new { @class = "form-control", type="number" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Số ĐT", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("sodt", null, new { @class = "form-control" })
                </div>
            </div>

        </div>
        <div class="form-group">
            @Html.Label("Ngày vào", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("ngay_vao", DateTime.Now, new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.ngay_ra, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Ngày ra", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("ngay_ra", null, new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.ngay_ra, "", new { @class = "text-danger" })
            </div>
        </div>
        @{
            if (ViewBag.select_ma_phong == null)
            {
                <div class="form-group">
                    @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ma_phong", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ma_phong, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.Label("Số phòng", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("ma_phong", (int)ViewBag.select_ma_phong, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })

                    </div>
                </div>
            }
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Đặt phòng" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("FindRoom","Index")">Back</a>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $('input[type=radio][name=radSelect]').change(function () {
            if (this.value == 'rad1') {
                $('#boxUser').show();
                $('#boxKH').hide();
            }
            else if (this.value == 'rad2') {
                $('#boxUser').hide();
                $('#boxKH').show();
            }
        });
    });
</script>