Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Controllers/LoaiPhongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Areas.Admin.Controllers
{
    public class LoaiPhongController : Controller
    {
        private dataQLKSEntities db = new dataQLKSEntities();

        // GET: LoaiPhong
        public ActionResult Index()
        {
            return View(db.tblLoaiPhongs.ToList());
        }

        // GET: LoaiPhong/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLoaiPhong tblLoaiPhong = db.tblLoaiPhongs.Find(id);
            if (tblLoaiPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblLoaiPhong);
        }

        // GET: LoaiPhong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiPhong/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mo_ta,gia,ti_le_phu_thu,anh")] tblLoaiPhong tblLoaiPhong)
        {
            if (ModelState.IsValid)
            {
                if (tblLoaiPhong.anh==null)
                    tblLoaiPhong.anh = "[\"/Content/Images/Phong/default.png\"]";
                db.tblLoaiPhongs.Add(tblLoaiPhong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblLoaiPhong);
        }

        // GET: LoaiPhong/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLoaiPhong tblLoaiPhong = db.tblLoaiPhongs.Find(id);
            if (tblLoaiPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblLoaiPhong);
        }

        // POST: LoaiPhong/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "loai_phong,mo_ta,gia,ti_le_phu_thu,anh")] tblLoaiPhong tblLoaiPhong)
        {
            if (ModelState.IsValid)
            {
                if (tblLoaiPhong.anh == null)
                    tblLoaiPhong.anh = "[\"/Content/Images/Phong/default.png\"]";
                db.Entry(tblLoaiPhong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblLoaiPhong);
        }

        // GET: LoaiPhong/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLoaiPhong tblLoaiPhong = db.tblLoaiPhongs.Find(id);
            if (tblLoaiPhong == null)
            {
                return HttpNotFound();
            }
            return View(tblLoaiPhong);
        }

        // POST: LoaiPhong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                tblLoaiPhong tblLoaiPhong = db.tblLoaiPhongs.Find(id);
                db.tblLoaiPhongs.Remove(tblLoaiPhong);
                db.SaveChanges();
            }
            catch
            {

            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/LoaiPhong/Create.cshtml
@model QLKS.Models.tblLoaiPhong

@{
    ViewBag.Title = "Thêm loại phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","LoaiPhong")">Loại phòng</a>
    </li>
    <li class="breadcrumb-item active">Thêm loại phòng</li>
</ol>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.Label("Tên loại phòng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mo_ta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mo_ta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Giá", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
            @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Tỉ lệ phụ thu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ti_le_phu_thu, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
            @Html.ValidationMessageFor(model => model.ti_le_phu_thu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="row container">
            <div class="col-md-6">
                <input type="file" id="FileUpload1" multiple class="form-control" />
            </div>
            @*<div class="col-md-3">
            <input type="button" id="btnUpload" value="Upload Files" class="btn" />
        </div>*@
        </div>
    </div>

    <div id="img"></div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.Editor("anh", null, new { htmlAttributes = new { @class = "form-control hidden" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Xác nhận" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>

$(document).ready(function(){
    $('#btnUpload').click(function () {

        // Checking whether FormData is available in browser
        if (window.FormData !== undefined) {

            var fileUpload = $("#FileUpload1").get(0);
            var files = fileUpload.files;

            // Create FormData object
            var fileData = new FormData();

            // Looping over all files and add it to FormData object
            for (var i = 0; i < files.length; i++) {
                fileData.append(files[i].name, files[i]);
            }

            // Adding one more key to FormData object
            fileData.append('username', 'Manas');

            $.ajax({
                url: '/Admin/Index/UploadFiles',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                    var obj = JSON.parse(result);
                    var code = "";
                    for (var i = 0; i < obj.length; i++) {
                        code += '<img src="' + obj[i] + '" style="height:200px;padding:3px"/>';
                    }
                    $('#img').html(code);
                    $('#anh').val(result);
                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        } else {
            alert("FormData is not supported.");
        }
    });
});
</script>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/LoaiPhong/Delete.cshtml
@model QLKS.Models.tblLoaiPhong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblLoaiPhong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mo_ta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mo_ta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/LoaiPhong/Details.cshtml
@model QLKS.Models.tblLoaiPhong

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblLoaiPhong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mo_ta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mo_ta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.loai_phong }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/LoaiPhong/Edit.cshtml
@model QLKS.Models.tblLoaiPhong

@{
    ViewBag.Title = "Sửa loại phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Admin</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","LoaiPhong")">Loại phòng</a>
    </li>
    <li class="breadcrumb-item active">Sửa loại phòng</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.loai_phong)

    <div class="form-group">
        @Html.Label("Loại phòng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mo_ta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mo_ta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Giá", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Tỉ lệ phụ thu", htmlAttributes: new { @class = "control-label col-md-2", max="30" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ti_le_phu_thu, new { htmlAttributes = new { @class = "form-control",type="number" } })
            @Html.ValidationMessageFor(model => model.ti_le_phu_thu, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="row container">
            <div class="col-md-6">
                <input type="file" id="FileUpload1" multiple class="form-control" />
            </div>
            <div class="col-md-3">
                <input type="button" id="btnUpload" value="Xác nhận" class="btn" />
            </div>
        </div>
    </div>

    <div id="img">
        @{
            String s = Model.anh;
            try
            {
                List<String> dsImg = Newtonsoft.Json.JsonConvert.DeserializeObject<List<String>>(s);
                foreach (String m in dsImg)
                {
                    <img src="@m" class="rounded" style="height:200px;padding:3px" />
                }
            }
            catch { }
        }
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.anh, new { htmlAttributes = new { @class = "form-control hidden" } })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trang chủ", "Index")
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>

$(document).ready(function(){
    $('#btnUpload').click(function () {

        // Checking whether FormData is available in browser
        if (window.FormData !== undefined) {

            var fileUpload = $("#FileUpload1").get(0);
            var files = fileUpload.files;

            // Create FormData object
            var fileData = new FormData();

            // Looping over all files and add it to FormData object
            for (var i = 0; i < files.length; i++) {
                fileData.append(files[i].name, files[i]);
            }

            // Adding one more key to FormData object
            fileData.append('username', 'Manas');

            $.ajax({
                url: '/Admin/Index/UploadFiles',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                    var obj = JSON.parse(result);
                    var code = "";
                    for (var i = 0; i < obj.length; i++) {
                        code += '<img src="' + obj[i] + '" style="height:200px;padding:3px"/>';
                    }
                    $('#img').html(code);
                    $('#anh').val(result);
                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        } else {
            alert("FormData is not supported.");
        }
    });
});
</script>

Hotel-Management-ASP.NET-MVC-main/QLKS/Areas/Admin/Views/LoaiPhong/Index.cshtml
@model IEnumerable<QLKS.Models.tblLoaiPhong>

@{
    ViewBag.Title = "Danh sách phòng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Index")">Trang chủ</a>
    </li>
    <li class="breadcrumb-item active">Danh sách loại phòng</li>
</ol>
<p>
    <!--@Html.ActionLink("Thêm loại phòng", "Create")-->
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh sách loại phòng
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mô tả</th>
                        <th>
                            Loại phòng
                        </th>
                        <th>
                            Giá
                        </th>
                        <th>
                            Tỉ lệ phụ thu
                        </th>
                        <!--<th></th>-->
                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @{
                            String m = (item.anh);
                            try
                            {
                                List<String> a = Newtonsoft.Json.JsonConvert.DeserializeObject<List<String>>(m); // from json to object
                                    <div><img src="@a[0]" height="50px" /></div>
                            }
                            catch { }
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.mo_ta)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.gia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ti_le_phu_thu)
                        </td>
                            
                        <!--
                        <td>
                            @Html.ActionLink("Sửa", "Edit", new { id = item.loai_phong }) 
                            @Html.ActionLink("Delete", "Delete", new { id = item.loai_phong })
                        </td>
                        -->
                            
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Last updated at @DateTime.Now</div>
</div>